"""add incident_analyses table

Revision ID: 0d25f6c90fc4
Revises: ebdb42f4ce0d
Create Date: 2026-08-31 13:16:53.029245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d25f6c90fc4'
down_revision: Union[str, None] = 'ebdb42f4ce0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('possible_causes', sa.JSON(), nullable=False),
    sa.Column('recommended_actions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_analyses_alert_id'), 'incident_analyses', ['alert_id'], unique=False)
    op.create_index(op.f('ix_incident_analyses_created_at'), 'incident_analyses', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incident_analyses_created_at'), table_name='incident_analyses')
    op.drop_index(op.f('ix_incident_analyses_alert_id'), table_name='incident_analyses')
    op.drop_table('incident_analyses')
    # ### end Alembic commands ###
